# ---- Site basics ----
title: "Ishara Paranawithana"
email: "isharackp@hotmail.com"
description: "A showcase of my projects and a personal blog documenting my journey."
url: "https://isharap.github.io"
baseurl: ""                        # Keep empty for user site
repository: "IsharaP/isharap.github.io" # Github repository
twitter_username: isharackp
github_username: IsharaP
search: true
codeenable_copy_code_button: true

# ---- Minimal Mistakes theme ----
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# ---- Plugins ----
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# ---- Author / social ----
author:
  name: "Ishara Paranawithana"
  avatar: "/assets/images/profile.jpeg"
  bio: "Data Scientist"
  location: "Melbourne, Australia"
  links:
    - label: "CV"
      icon: "fas fa-file-alt"      # or: "far fa-file-pdf"
      url: "/assets/files/CV.pdf"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:isharackp@hotmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/IsharaP"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ishara-paranawithana/"

# ---- Page defaults ----
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      toc: true
      toc_sticky: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/isharackp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/IsharaP"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ishara-paranawithana/"

# ---- Build ----
markdown: kramdown
permalink: /:title/
