# ---- Site basics ----
title: "Ishara Paranawithana"
name: "Ishara"
url: "https://isharap.github.io"   # no trailing slash
baseurl: ""                        # keep empty for user site

# ---- Minimal Mistakes theme ----
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# ---- Plugins ----
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

# ---- Author / social ----
author:
  name: "Ishara Paranawithana"
  avatar: "/assets/images/profile.jpeg"
  bio: "Scientist @ CSIRO | PhD ECSE (Biomedical Eng). Medical Imaging • CV • NeuroTech • Applied AI/ML"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/IsharaP"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/ishara-paranawithana/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:isharackp@hotmail.com"   # <-- add mailto:

# ---- Page defaults ----
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      toc: true
      toc_sticky: true

# ---- Build ----
markdown: kramdown
permalink: /:title/
